language: rust
sudo: false
rust:
    - nightly

branches:
    only:
        - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc-5
            - g++-5
            - binutils-dev
            - libiberty-dev
            - valgrind
env:
    - CC=gcc-5 CXX=g++-5 RUSTFLAGS='-C link-dead-code'

script:
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    - cargo clippy --all -- -D warnings
    - cargo test
    - mkdir build
    - ( cd build && cmake .. && make )
    - ( cd bin/x86_64 && ldd ./cpp-raw && valgrind --error-exitcode=1 ./cpp-raw )
    - ( cd bin/x86_64 && ldd ./cpp-wrapper && valgrind --error-exitcode=1 ./cpp-wrapper )
    - ( cd bin/x86_64 && ldd ./cpp-dl && valgrind --error-exitcode=1 ./cpp-dl )
