
version: "{build}"

branches:
    only:
        - master

os:
    - Visual Studio 2017
      # - Visual Studio 2015
      # - Visual Studio 2013

environment:
    matrix:
    - TARGET: x86_64-pc-windows-msvc

      # Disable the GNU target for now as it's broken. Rust #47029
      #- TARGET: nightly-x86_64-pc-windows-gnu


install:
    - curl -sSf -o rustup-init.exe https://win.rustup.rs
    - rustup-init.exe --default-host %TARGET% --default-toolchain nightly -y
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -vV
    - cargo -vV
    - rustup component add rustfmt-preview

before_build:
    - nuget restore test\cs\cs.sln

platform:
    - x64

build_script:
    - cmd: .\scripts\ci.bat

test_script:
    - cargo test --release
    - ps: .\scripts\test.ps1
