
version: 2

jobs:
    build:
        docker:
            - image: rustlang/rust:nightly
              environment:
                  RUSTFLAGS: -C link-dead-code

        steps:
            - checkout
            - run:
                name: "Report versions"
                command: |
                    rustc -vV
                    cargo -vV
            - run:
                name: "Install rustfmt"
                command: |
                    rustup component add rustfmt-preview
            - run:
                name: "Cargo test"
                command: |
                    export RUST_BACKTRACE=1
                    cargo test --all-features
            - run:
                name: "C++ test"
                command: |
                    gcc --version
                    g++ --version
                    apt-get update
                    apt-get install cmake -y
                    cmake --version
                    mkdir build
                    cd build
                    cmake ..
                    make
                    cd ../bin/x86_64
                    ./cpp-raw
